### ISSUE TITLE
Plugin disapeared after upgrading to Unraid 6.9.0-rc2 and does not allow to reinstall

### ISSUE THREAD

**Issue by rmaenk** [JTok/unraid.vmbackup#25]
Hello,

I have upgarded to latest version of Unraid and the pluging disapeared from list of installed plugins.
Attempts to install using dirrect link from GitHub produces the next messages:
```
plugin: installing: https://raw.githubusercontent.com/jtok/unraid.vmbackup/master/vmbackup.plg
plugin: downloading https://raw.githubusercontent.com/jtok/unraid.vmbackup/master/vmbackup.plg
plugin: downloading: https://raw.githubusercontent.com/jtok/unraid.vmbackup/master/vmbackup.plg ... done
plugin: installed Unraid version is too high, require at most version 6.8.3
```

Is it really unsupported for some reason or just not updated plugin config?

PS: Thanks for your effort - plugin is very useful!

Regards, Roman

**Comment by burntoc** [comment]
I probably screwed up the process somehow, but using the link wouldn't complete because of a URL error somewhere in the script.  I foolishly uninstalled my existing version and I tried the v21 and v22 file URLs and I couldn't get that either.  I will probably try downloading them to install locally b/c I want to get it back.   If that fails, can the dev post the steps needed to bypass that check for those of us that are willing to take the risk until a tested version is available?

Edit:  And I really appriate your putting this plugin  out there, too!

**Comment by JTok** [comment]
I removed the version restriction on the latest version.
